services:
  snomed-neo4j:
    build: .
    ports:
      - "7474:7474" # HTTP
      - "7473:7473" # HTTPS
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=neo4j/neo4jneo4j
      - SNOMED_DATA_SOURCE=mount
      - SNOMED_SLIM_MODE=false
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      # - ./data/snomed:/data/snomed
      - ./data/neo4j_data:/data
      - ./data/neo4j_plugins:/plugins
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7474"]
      interval: 10s
      timeout: 5s
      retries: 5
