# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Core Package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      # - name: Run tests
      #   # For example, using `pytest`
      #   run: uv run pytest tests

      # - name: Run tests
      #   # For example, using `pytest`
      #   run: uv run pytest tests
